M48
; DRILL file {KiCad 9.0.0} date 2026-04-28T00:09:46+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-28T00:09:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X218.85Y-79.85
T2
X136.05Y-137.3
M30
