M48
; DRILL file {KiCad 9.0.0} date 2026-05-14T18:01:27-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-14T18:01:27-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X218.85Y-79.85
T2
X125.245Y-137.3
M30
